apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-config
  namespace: k8s-dashboard
  
data:
  # Simple key-value pairs (Environment Variables)
  UI_COLOR: "blue"
  LOG_LEVEL: "debug"
  
  # Multi-line strings (Configuration Files)
  settings.properties: |
    max.connections=20
    timeout=30s
    feature.flag.beta=true
